app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),unique = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    post = db.relationship('Post',backref = 'user',lazy = 'dynamic')
    comments = db.relationship('Comment',backref = 'user',lazy = 'noload')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer,primary_key = True)
    post_category = db.Column(db.String)
    post_title = db.Column(db.String)
    post_text = db.Column(db.String)
    post_time = db.Column(db.DateTime, default = datetime.utcnow)
    post_votes = db.Column(db.Integer)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments = db.relationship('Comment',backref = 'post',lazy = 'dynamic')
    
    def save_post(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_posts(cls,category):
        posts = Post.query.filter_by(post_category = category).order_by(Post.post_time.desc()).all()
        print(posts)
        return posts

    @classmethod
    def get_user_posts(cls,user):
        posts = Post.query.\
            filter_by(user_id = user).\
            order_by(Post.post_time).all()
        return posts


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment_text = db.Column(db.String)
    comment_time = db.Column(db.DateTime, default = datetime.utcnow)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(post_id = id).all()
        return  comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField, SelectField
from wtforms.validators import Required, DataRequired


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [DataRequired()])
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    pitch = SelectField('pitch',choices=[('pickup lines','pickup lines'),('interview pitch','interview pitch'),('product pitch','product pitch')])
    title = StringField('Post title',validators=[DataRequired()])
    post = TextAreaField('Write your post',validators=[DataRequired()])
    submit = SubmitField('submit')

class CommentForm(FlaskForm):
    comment = TextAreaField('Write your comment',validators=[DataRequired()])
    submit = SubmitField('submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos= UploadSet('photos',IMAGES)
mail = Mail()

simple = SimpleMDE()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations

    app.config.from_object(config_options[config_name])
    # config_options[config_name].init_app(app)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)
    
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # setting config
    # from .request import configure_request
    # configure_request(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    # config uploadset
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint 

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import PostForm, CommentForm, UpdateProfile
from ..models import User, Post, Comment
from flask_login import login_required, current_user
from .. import db, photos


@main.route('/')
def index():

  title = 'Home - Welcome to Pitch'

  return render_template('index.html', title = title)


@main.route('/pitch/<pitch_name>' )
def pitch(pitch_name):

  pitch = pitch_name
  title = f'{pitch}'
  post = Post.get_posts(pitch)
  print(post)

  return render_template('category.html', title = title, pitch = pitch, posts = post)


@main.route('/pitch/comments/<int:id>')
def comments(id):
  title = 'Comments'
  comments = Comment.get_comments(id)

  return render_template('comments.html', title = title, comments = comments )

@login_required
@main.route('/pitch/post/new/<pitch_name>', methods = ['GET','POST']) 
def new_post(pitch_name):
  form = PostForm()
  pitch = pitch_name
  
  if form.validate_on_submit():
      title = form.title.data
      post = form.post.data
      print(title)
      new_post = Post( post_title = title, post_text = post, post_votes = 0, user=current_user,post_category=pitch_name )
      new_post.save_post()
      return redirect(url_for('.pitch',pitch_name=pitch))

  title = 'New Post'
  return render_template('new_post.html', title= title, form= form, pitch= pitch)


@main.route('/pitch/post/comments/new/<int:id>', methods = ['GET', 'POST'])
@login_required
def new_comment(id):
  form = CommentForm()
  print(id)

  if form.validate_on_submit():
    post_id = id
    comment = form.comment.data
    print(comment)
    new_comment = Comment(comment_text= comment,post_id= post_id, user_id= current_user.id)
    new_comment.save_comment()
    return redirect(url_for('.view_post',id = id))

  title = 'New Comment'
  return render_template('new_post.html', title= title, form= form)


@main.route('/post/view/<int:id>', methods=['GET', 'POST'])
@login_required
def view_post(id):
    test = id
    print(test)
    print('test')
    post = Post.query.filter_by(id=id).first()
    print(post.post_text)
    comments = Comment.get_comments(id)
    return render_template('view.html',post=post, comments=comments, id=id)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
    print(user.id)
    post = Post.query.filter_by(user_id=user.id).order_by(Post.post_time.desc()).all()

    return render_template('profile/profile.html',user = user,post=post)



@main.route('/user/<uname>/update', methods=['GET', 'POST'])
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()
    
    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname = user.username))

    return render_template('profile/update.html',form = form)


@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html' %}


{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <link rel="stylesheet" type= "text/css" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

app/templates/category.html
{% extends 'base.html' %}
<!-- content block -->

{% block content %}
<div id="category" style="text-align: center;">
  <h2 style="color: aqua;">Welcome to {{category | title }}</h2>
  <a class="btn btn-primary text-center " href="{{url_for('main.new_post', pitch_name=pitch)}}">
    </span> Add a Pitch</a>
  <hr>

  <div class="post">
    {% for post in posts %}

    <div class="panel panel-primary" style="width:70%;text-align:center; background-color: #0F2027">
      <div class="panel-heading">
        <h2 class="panel-title" style="font-size: 30px;">{{post.post_title}}</h2>
      </div>
      <div class="panel-body">
        <p class='firstletter'>{{post.post_text}}</p>
      </div>
      <div class="panel-footer"><a class="btn btn-info text-center"
          href="{{url_for('main.view_post', id=post.id)}}">Comments</a></div>
    </div>
    {% endfor %}

    {% endblock %}
  </div>
</div>

app/templates/fourOwfour.html
{% extends 'base.html'%}
{% block content %}
<div id="notfound">
	<div class="notfound">
		<div class="notfound-404">
			<h1>404</h1>
			
			<h2>Connection error,try again</h2>
		</div>
		<a href="/">Homepage</a>
	</div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

{% block styles%}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/index.css')}}">


{% endblock %}


{% block content %}


<h1>WELCOME TO ONE MINUTE PITCH.</h1>
<hr>
<br><br>
<p>In life, you only have 60 seconds to impress someone. 1 minute can make or break you.</p>
<br>
<p>Use your 1 minute to  say something meaningful.</p>

<br><br><br>

{% endblock%}

app/templates/navbar.html
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>

      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->


    <div class="links">
      <a class="btn btn-primary btn-lg" href="{{url_for('main.pitch',pitch_name='pickuplines')}}">Pitches</a>
      <a class="btn btn-outline-danger" style="font-size:x-large;" href="/pitch/pickup lines pitch"> pickup lines</a>
      <a class="btn btn-outline-danger" style="font-size:x-large;" href="/pitch/Music pitch"> Music</a>
      <a class="btn btn-outline-danger" style="font-size:x-large;" href="/pitch/Employments pitch">Employments </a>
      <a class="btn btn-outline-danger" style="font-size:x-large;" href="/pitch/promotion pitch">Business</a>
      <a class="btn btn-outline-danger" style="font-size:x-large;" href="{{url_for('auth.register')}}">Sign-up</a>
      {% if current_user.is_authenticated %}

      <a class="btn btn-outline-primary" style="font-size:x-large;" id="profile"
        href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
      <a class="btn btn-outline-primary" style="font-size:x-large;" id="sign" href="{{url_for('auth.logout')}}">Sign
        out</a>
      {% else %}
      <a class="btn btn-outline-primary" id="sign" style="font-size:x-large;" href="{{url_for('auth.login')}}">Sign
        in</a>
      {%endif%}

    </div>
  </div>
</nav>

app/templates/new_comments.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends 'base.html'%}



{% block content %}

<div class="container" style="color: white">



 
    {{ wtf.quick_form(form) }}

</div>

{% endblock %}

app/templates/new_post.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends 'base.html'%}



{% block content %}

<div class="container" style="color: white; width: 50%;">

    {{ wtf.quick_form(form) }}

</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <h1> {{user.username| capitalize}} </h1>
        <hr>
        <br><br><br>
        <!--Displaying user bio-->
        <div class="col-md-3">
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>
        <div class="col-sm-3">
            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" style="text-align: center">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
        </div>
        <div class="col-sm-3">
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input class="btn btn-primary text-center" type="submit">
            </form>
            {% endif %}
        </div>
        <div class="col-sm-3">
            {% if user == current_user %}
            <a class="btn btn-primary text-center" href="{{url_for('main.update_profile',uname=user.username)}}">Edit
                profile</a>
            {% endif %}
        </div>
    </div>

    {% for post in posts %}
    <h3>{{post.post_title}}</h3>
    <p>{{post.post_text}}</p>
    <div class="panel-footer"><a class="btn btn-primary text-center" href="{{url_for('main.new_post', id=post.id)}}">View Comments</a><a href="/comment/4">comment</a>

        {% endfor %}
    </div>
    {% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
{% extends 'base.html' %}
<div class="container" style="color: white">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/view.html
{% extends 'base.html' %}
<!-- content block -->
{% block content %}

<div class="view" style="color: cyan; text-align: center">
  <h2 id='view-title'>{{post.post_title}}</h2>
  <p class='content firstletter '>{{post.post_text}}</p>

  <br>
  <hr>
  <a class="btn btn-primary text-center " style="width:25%; " href="{{url_for('main.new_comment', id=post.id)}}">say
    something</a>

  <br>
  <br>
  
    {% for comment in comments %}
  
  <div class="panel panel-default" class='panel-view'>

    <div class="panel-body">
      <p class='firstletter' style="color: black;">{{comment.comment_text}}</p>
    </div>

  </div>
  {% endfor %}
</div>
{% endblock %}